project:
  type: website
  output-dir: docs

website:
  title: 'DSA'
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
  sidebar:
    - text: Basic Sorting
      href: sorting/index.qmd
      contents:
        - text: Bubble Sort
          href: sorting/bubble.qmd
        - text: Merge Sort
          href: sorting/merge.qmd
    - text: Advanced Sorting
      href: sorting/index.qmd
      contents:
        - text: Bubble Sort
          href: sorting/bubble.qmd
        - text: Merge Sort
          href: sorting/merge.qmd
