project:
  type: website
  output-dir: docs

website:
  title: 'DSA'
  favicon: favicon.ico
  navbar:
    background: primary
    left:
      - text: Home
        href: https://nachiketpatil0105.github.io/home/
      - text: About Me
        href: https://nachiketpatil0105.github.io/home/profile
      - text: DSA Notes
        href: index.qmd
  sidebar:
    style: docked
    collapse-level: 1
    search: true
    contents:
      - section: 'Basic Sorting'
        contents:
          - text: Bubble Sort
            href: DSA Notes/Basic Sorting/Bubble_Sort.qmd
          - text: Selection Sort
            href: DSA Notes/Basic Sorting/Selection_Sort.qmd
          - text: Insertion Sort
            href: DSA Notes/Basic Sorting/Insertion_Sort.qmd
      - section: 'Advanced Sorting'
        contents:
          - text: Quick Sort
            href: DSA Notes/Advanced Sorting/Quick_Sort.qmd
          - text: Merge Sort
            href: DSA Notes/Advanced Sorting/Merge_Sort.qmd
      - section: 'Binary Search'
        contents:
          - text: Binary Search
            href: DSA Notes/Binary_Search.qmd
          - text: BS in Rotated Array (No Duplicates)
            href: DSA Notes/BS_rotated_no_dupli.qmd
          - text: BS in Rotated Array (Duplicates)
            href: DSA Notes/BS_rotated_Dupli.qmd

format:
  html:
    theme:
      - cosmo
      # - custom.scss
    css: styles.css
