project:
  type: website
  output-dir: docs

website:
  title: 'DSA'
  favicon: favicon.ico
  navbar:
    background: primary
    left:
      - text: Home
        href: https://nachiketpatil0105.github.io/home/
      - text: About Me
        href: https://nachiketpatil0105.github.io/home/profile
      - text: DSA Notes
        href: index.qmd
  sidebar:
    style: docked
    collapse-level: 1
    search: true
    contents:
      - section: 'C++ STL'
        contents:
          - text: Vector
            href: DSA Notes/C++STL/vector.qmd
          - text: String
            href: DSA Notes/C++STL/string.qmd
          - text: Char
            href: DSA Notes/C++STL/char.qmd
          - text: Deque
            href: DSA Notes/C++STL/deque.qmd
          - text: List
            href: DSA Notes/C++STL/list.qmd
          - text: Stack
            href: DSA Notes/C++STL/stack.qmd
          - text: Queue
            href: DSA Notes/C++STL/queue.qmd
          - text: Priority Queue
            href: DSA Notes/C++STL/priority_queue.qmd
          - text: Set
            href: DSA Notes/C++STL/set.qmd
          - text: Map
            href: DSA Notes/C++STL/map.qmd
          - text: Algorithm
            href: DSA Notes/C++STL/algorithm.qmd
      - section: 'Basic Sorting'
        contents:
          - text: Bubble Sort
            href: DSA Notes/Basic Sorting/Bubble_Sort.qmd
          - text: Selection Sort
            href: DSA Notes/Basic Sorting/Selection_Sort.qmd
          - text: Insertion Sort
            href: DSA Notes/Basic Sorting/Insertion_Sort.qmd
      - section: 'Advanced Sorting'
        contents:
          - text: Quick Sort
            href: DSA Notes/Advanced Sorting/Quick_Sort.qmd
          - text: Merge Sort
            href: DSA Notes/Advanced Sorting/Merge_Sort.qmd
      - section: 'Binary Search'
        contents:
          - text: Binary Search
            href: DSA Notes/Binary Search/Binary_Search.qmd
          - text: BS in Rotated Array (No Duplicates)
            href: DSA Notes/Binary Search/BS_rotated_no_dupli.qmd
          - text: BS in Rotated Array (Duplicates)
            href: DSA Notes/Binary Search/BS_rotated_dupli.qmd
      - section: 'Recursion'
        contents:
          - text: Recursion
            href: DSA Notes/Recursion/recursion.qmd
          - text: Finding the Power Set
            href: DSA Notes/Recursion/finding_power_set.qmd
          - text: Paring of Two or Multiple Arrays
            href: DSA Notes/Recursion/pairing_two_or_multiple_sets.qmd
      - section: 'Linked List'
        contents:
          - text: Singly Linked List
            href: DSA Notes/Linked List/sll.qmd
          - text: Doubly Linked List
            href: DSA Notes/Linked List/dll.qmd
          - text: Circular Linked List
            href: DSA Notes/Linked List/cll.qmd
      - section: 'Stack'
        contents:
          - text: Creation of Stack
            href: DSA Notes/Stack/creation.qmd

format:
  html:
    theme:
      - cosmo
      # - custom.scss
    css: styles.css
