project:
  type: website
  output-dir: docs

website:
  title: 'DSA'
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
  sidebar:
    style: 'docked'
    search: true
    contents:
      - section: 'Basic Sorting'
        contents:
          - text: Bubble Sort
            href: DSA Notes/Basic Sorting/Bubble_Sort.qmd
          - text: Selection Sort
            href: DSA Notes/Basic Sorting/Selection_Sort.qmd
          - text: Insertion Sort
            href: DSA Notes/Basic Sorting/Insertion_Sort.qmd
      - section: 'Advanced Sorting'
        contents:
          - text: Quick Sort
            href: DSA Notes/Advanced Sorting/Quick_Sort.qmd
          - text: Merge Sort
            href: DSA Notes/Advanced Sorting/Merge_Sort.qmd
